name: Check Mirrors
on:
  schedule: [{ cron: "0 22 * * *" }]
  workflow_dispatch: null
  pull_request: { paths: ["assets/community-mirrors.ziggy"] }
jobs:
  check:
    runs-on: [self-hosted, website]
    steps:
      - uses: actions/checkout@v2
      - name: Check Mirrors
        run: |
          cd check-mirrors
          /home/ci/deps/zig-linux-x86_64-0.14.0/zig build run -- ../assets/community-mirrors.ziggy "$GITHUB_STEP_SUMMARY"
  notify-failure:
    runs-on: [self-hosted, website]
    needs: [check]
    if: ${{ always() && (needs.check.result == 'failure' || needs.check.result == 'timed_out') }}
    steps:
      - name: Send Notification
        env:
          PUSHOVER_USER: ${{ secrets.MIRROR_CHECK_PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.MIRROR_CHECK_PUSHOVER_TOKEN }}
        run: curl -s
               -F user="$PUSHOVER_USER"
               -F token="$PUSHOVER_TOKEN"
               -F message="Zig download mirror validation failed"
               https://api.pushover.net/1/messages.json
